system:
  serial_port: "/dev/ttyUSB0"
  enable_logging: true

hardware:
  has_spa: true
  has_pool_heater: true
  has_spa_heater: true
  has_pool_lights: true
  has_spa_lights: true
  has_deck_lights: false
  has_blower: true
  has_solar: true
  has_cleaner: true
